[package]
name = "homer"
version = "0.2.3"
authors = ["Christian Mutti <chrsmutti@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
crossterm = { version = "0.27", default-features = false }
clap = { version = "4.5.4", features = ["derive", "env"] }
