[package]
name = "homer"
version = "0.2.2"
authors = ["Christian Mutti <chrsmutti@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
structopt = "0.3.19"
anyhow = "1.0.33"
crossterm = "0.18.0"
