name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Add target
        run: rustup target add x86_64-apple-darwin

      - name: Build
        run: cargo build --release --target x86_64-apple-darwin

      - name: Rename binary
        run: mv target/x86_64-apple-darwin/release/homer  homer_${{ steps.get_version.outputs.VERSION }}_x86_64-apple-darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: homer_${{ steps.get_version.outputs.VERSION }}_x86_64-apple-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Add target
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Rename binary
        run: mv target/x86_64-unknown-linux-gnu/release/homer  homer_${{ steps.get_version.outputs.VERSION }}_x86_64-unknown-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: homer_${{ steps.get_version.outputs.VERSION }}_x86_64-unknown-linux-gnu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
