name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build
        run: cargo build --release --target apple-darwin-x86_64

      - name: Rename binary
        run: mv target/apple-darwin-x86_64/release/homer  homer_${{ steps.get_version.outputs.VERSION }}_apple-darwin-x86_64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: homer_${{ steps.get_version.outputs.VERSION }}_apple-darwin-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build
        run: cargo build --release --target unknown-linux-gnu

      - name: Rename binary
        run: mv target/unknown-linux-gnu/release/homer  homer_${{ steps.get_version.outputs.VERSION }}_unknown-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: homer_${{ steps.get_version.outputs.VERSION }}_unknown-linux-gnu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
