name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    strategy:
      matrix:
        target: 
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macOS-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.target.os }}
    env:
      TARGET: ${{ matrix.target.target }}
    steps:
      - uses: actions/checkout@v4

      - name: Add target
        run: rustup target add ${TARGET}

      - name: Build
        run: cargo build --release --target ${TARGET}

      - name: Rename binary
        run: mv target/${TARGET}/release/homer homer_${GITHUB_REF_NAME}_${TARGET}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: homer_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
