name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-18.04]
        arch: [x86_64]
        include:
          - os: macOS-latest
            target: apple-darwin
          - os: ubuntu-18.04
            target: unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          targets: ${{ matrix.arch }}-${{ matrix.target }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build
        run: cargo build --release --target ${{ matrix.arch }}-${{ matrix.target }}

      - name: Archive
        run: tar cvf homer_${{ steps.get_version.outputs.VERSION }}_${{ matrix.arch }}-${{ matrix.target }}.tar.gz -C target/${{ matrix.arch }}-${{ matrix.target }}/release/ homer

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: homer_${{ steps.get_version.outputs.VERSION }}_${{ matrix.arch }}-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
